/**
 *
 * RSCLocalizedStrings
 *
 * This file is autogenerated by runScript.sh
 * Generates strings key macros
 *
 */



NSString * RSCLocalizedSring(NSString *strKey);

#define RSCSTR_CATEGORY           RSCLocalizedSring(kRSCStrCategory)
extern NSString * const kRSCStrCategory;

#define RSCSTR_COMPONENT           RSCLocalizedSring(kRSCStrComponent)
extern NSString * const kRSCStrComponent;

#define RSCSTR_PLAYGROUND           RSCLocalizedSring(kRSCStrPlayground)
extern NSString * const kRSCStrPlayground;

#define RSCSTR_STRUCTURE           RSCLocalizedSring(kRSCStrStructure)
extern NSString * const kRSCStrStructure;

