/**
 *
 * RSCLocalizedStrings
 *
 * This file is autogenerated by runScript.sh
 * Generates strings key macros
 *
 */



#import "RSCLocalizedStrings.h"

NSString* RSCLocalizedSring(NSString *strKey) {
    static NSString *VAL_NOT_FOUND = @"__VAL_NOT_FOUND__";
    NSString *localizedString = [[NSBundle mainBundle] localizedStringForKey:strKey value:VAL_NOT_FOUND table:nil];
    if ([localizedString isEqualToString:VAL_NOT_FOUND]) {
        if (![[[NSLocale preferredLanguages] objectAtIndex:0] isEqualToString:@"Base"]) {
            static NSBundle *EN_LANG_BUNDLE = nil;
            if (EN_LANG_BUNDLE == nil) {
                NSString *path = [[NSBundle mainBundle] pathForResource:@"Base" ofType:@"lproj"];
                EN_LANG_BUNDLE = [NSBundle bundleWithPath:path];
            }
            localizedString = [EN_LANG_BUNDLE localizedStringForKey:strKey value:@"" table:nil];
        } else {
            localizedString = @"";
        }
    }
    return localizedString;
}


NSString * const kRSCStrCategory      = @"category";
NSString * const kRSCStrTopTabs      = @"top_tabs";
NSString * const kRSCStrAccount      = @"account";
NSString * const kRSCStrBottomTabs      = @"bottom_tabs";
NSString * const kRSCStrFinance      = @"finance";
NSString * const kRSCStrSlideMenu      = @"slide_menu";
NSString * const kRSCStrIntroduction      = @"introduction";
NSString * const kRSCStrCommunication      = @"communication";
NSString * const kRSCStrSettings      = @"settings";
NSString * const kRSCStrComponent      = @"component";
NSString * const kRSCStrUtilities      = @"utilities";
NSString * const kRSCStrSocialNetwork      = @"social_network";
NSString * const kRSCStrPlayground      = @"playground";
NSString * const kRSCStrReading      = @"reading";
NSString * const kRSCStrEcommerce      = @"ecommerce";
NSString * const kRSCStrStructure      = @"structure";
